---
- hosts: all
  remote_user: root
  tasks:
    - name: install vim
      apt:
        name: vim
        state: present

- hosts: private_servers
  remote_user: root
  tasks:
    - name: replace resolv.conf for all sX.infra
      copy:
        src: /home/vagrant/ansible_config/templates/dnsmasq/resolv.conf
        dest: /etc/resolv.conf

- hosts: network
  remote_user: root
  tasks:
    - name: install dnsmasq
      apt:
        name: dnsmasq
        state: present
    - name: replace existing dnsmasq.conf
      copy:
        src: /home/vagrant/ansible_config/templates/dnsmasq/dnsmasq.conf
        dest: /etc/dnsmasq.conf

- hosts: web
  remote_user: root
  tasks:
    - name: install web packages
      apt:
        name:
          - apache2
          - php7.3
        state: present
    - name: start service
      service:
        name: apache2
        state: started
    - name: download wordpress
      get_url:
        url: https://fr.wordpress.org/latest-fr_FR.tar.gz
        dest: "/usr/src"
    - name: check if already exists
      stat:
        path: "/usr/src/wordpress"
      register: wordpress_directory
    - name: unzip it
      unarchive:
        remote_src: yes
        src: "/usr/src/latest-fr_FR.tar.gz"
        dest: "/usr/src"
      when: not wordpress_directory.stat.exists
    - name: rename wordpress
      command: "mv /usr/src/latest-fr_FR /usr/src/wordpress"
      when: not wordpress_directory.stat.exists
    - name: remove archive
      file:
        path: "/usr/src/latest-fr_FR.tar.gz"
        state: absent

- hosts: database
  remote_user: root
  tasks:
    - name: install mariaDB
      apt:
        name: mariadb
        state: present
    - name: start service
      service:
        name: mysql
        state: started

- hosts: nfs
  remote_user: root
  tasks:
    - name: install nfs server
      apt:
        name: nfs-kernel-server
        state: present